---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 51.250.112.140
      ansible_port: 22
      ansible_user: vitas
      ansible_ssh_private_key_file: "~/.ssh/id_yc_ed25519"
vector:
  hosts:
    vector-01:
      ansible_host: 130.193.35.244
      ansible_port: 22
      ansible_user: vitas
      ansible_ssh_private_key_file: "~/.ssh/id_yc_ed25519"
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 158.160.158.189
      ansible_port: 22
      ansible_user: vitas
      ansible_ssh_private_key_file: "~/.ssh/id_yc_ed25519"
