user                 {{ web_user }};
pid                  /run/nginx.pid;
worker_processes     auto;
worker_rlimit_nofile 65535;

include              /etc/nginx/modules-enabled/*.conf;

events {
    multi_accept       on;
    worker_connections 65535;
}

http {
    charset                utf-8;
    sendfile               on;
    tcp_nopush             on;
    tcp_nodelay            on;
    server_tokens          off;
    log_not_found          off;
    types_hash_max_size    2048;
    types_hash_bucket_size 64;
    client_max_body_size   16M;
    include                mime.types;
    default_type           application/octet-stream;
    access_log             /var/log/nginx/access.log;
    error_log              /var/log/nginx/error.log warn;

    include                /etc/nginx/conf.d/*.conf;
    include                /etc/nginx/sites-enabled/*;
}

